name: Run gradle build

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Upload workspace
        uses: actions/upload-artifact@v4
        with:
          name: workspace
          path: .

  build:
    needs: prepare
    uses: qupath/actions/.github/workflows/gradle.yml@main