name: Run gradle build

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    steps:
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - uses: qupath/actions/.github/workflows/gradle.yml@main